Repository krogowsk531/house-rules, pull requests merged in 2020-10, with the labels that each got.

#14 Api
  .gitignore
  components/CardPage/Cards/Cards.css
  components/CardPage/Cards/Cards.js
  components/CardPage/Cards/Cards.test.js
  components/SingleCard/SingleCard.js
  components/SingleCard/SingleCard.module.css
  components/SingleCard/SingleCard.test.js
  package.json
  pages/api/apiCalls.js
  pages/api/hello.js
  pages/index.js
Labels: Fetch, priority: 1, type: enhancement

#20 Features: render home page & single game page
  components/Cards/Cards.css
  components/Cards/Cards.js
  components/Cards/Cards.test.js
  components/NavBar/NavBar.js
  components/RuleDisputeForm/RuleDisputeForm.js
  components/RuleDisputeForm/RuleDisputeForm.test.js
  components/SingleCard/SingleCard.js
  pages/GameDetails/[gameid].js
  pages/api/apiCalls.js
  pages/index.js
  pages/sample/index.js
Labels: Fetch, issue: question, type: enhancement, type: refactor

#28 Form
  .babelrc
  components/Cards/Cards.js
  components/NavBar/NavBar.test.js
  components/RuleDisputeForm/RuleDisputeForm.js
  components/SingleCard/SingleCard.js
  components/SingleCard/SingleCard.test.js
  jest.config.js
  package-lock.json
  package.json
  pages/GameDetails/[gameid].js
  pages/index.js
  setupTests.js
Labels: test: unit, type: bug, type: enhancement
