Repository krogowsk531/house-rules, pull requests merged in 2020-11, with the labels that each got.

#31 Jest config
  .babelrc
  __mocks__/fileMock.js
  __mocks__/styleMock.js
  components/SingleCard/SingleCard.js
  jest.config.js
  package-lock.json
  package.json
  tests/setup.js
  tests/setupAfterEnv.js
Labels: priority: 1, type: bug

#38 Dispute rules
  components/Cards/Cards.js
  components/Comments/Comments.js
  components/RuleDisputeForm/RuleDisputeForm.js
  components/RuleDisputeForm/RuleDisputeForm.test.js
  components/RuleDisputes/RuleDisputes.js
  hooks/hooks.js
  pages/GameDetails/[gameid].js
  pages/index.js
Labels: priority: 1, type: documentation, type: enhancement

#47 Built README
  README.md
Labels: priority: 1, type: documentation

#48 Dispute comments & Tests for Dispute Rules
  components/Cards/Cards.test.js
  components/Comments/Comments.js
  components/Comments/Comments.test.js
  components/RuleDisputes/RuleDisputes.js
  components/RuleDisputes/RuleDisputes.test.js
Labels: priority: 1, test: integration/acceptance, test: unit, type: documentation, type: enhancement
